const chatLines = [
  "La vaca que ríe: ‎Los mensajes y las llamadas están cifrados de extremo a extremo. Solo las personas en este chat pueden leerlos, escucharlos o compartirlos.",
  "Ana: ‎Ana creó el grupo “Finde Málaga ”.",
  "La vaca que ríe: ‎Ana te añadió.",
  "Luigi: ‎Ana añadió a Luigi.",
  "Ana: https://www.booking.com/hotel/es/suncity-flat-salitre-6.es.html",
  "Ana: https://www.booking.com/hotel/es/los-tilos-suites-vialia.es.html",
  "Ana: https://www.booking.com/hotel/es/estacion-centro-vialia-apartamento.es.html",
  "Ana: https://www.booking.com/hotel/es/tuguest-heroe-apartment.es.html",
  "Ana: Para decidir... y después seguimos en el otro",
  "Xoana: Venga lo veo ahora",
  "Lolina: Eso son hoteles?",
  "Boque: Ok",
  "Boque: En cuanto pueda los miro 😀",
  "Lolina: Más versatilidad nos da un apartamento no?",
  "Lolina: Lo digo por si vienen laura y alguien más",
  "Boque: Lo suyo sería reservar un par de sitios: uno mínimo para los que estamos confirmados ya",
  "Boque: Y otro para los posibles que vengan",
  "Boque: Y el segundo se cancela en caso de que no vengan",
  "Xoana: Son apartamentos",
  "Xoana: Sí",
  "Xoana: Yo busqué para 7 contando con Luis y Laura que hará todo lo posible por venir",
  "Alberto: Luego los veo! Gracias!",
  "Xoana: @34671447567 si nos descartas alguno tú qué veas por el tema de la zona/calle en la que esté guay. Y ¿los que habías enviado tú no nos quedaban bien? ¿Los descartamos?",
  "Boque: Esperad, que estoy dando clase 😅 ‎<Se editó este mensaje.>",
  "Boque: Esta tarde le echo un vistazo a todos",
  "Alberto: Jajajjas",
  "Alberto: Te van a confiscar el móvil tus alumnos",
  "Xoana: 😂",
  "Xoana: ¿De qué les estás hablando hoy?",
  "Boque: Pues ahora mismo en 4º estamos viendo la proclamación de la IIª República",
  "Boque: Les he puesto un video y por eso puedo escribir desde el fondo de la clase",
  "Boque: Pero no puedo ponerme a ver en detalle los apartamentos que habéis mandado 😂😂😂",
  "Boque: Con los de 1º acabo de terminar Egipto y Mesopotamia",
  "Xoana: Qué maravilla.",
  "Xoana: Puedes con eso y mucho más.",
  "Alberto: Jajajaja",
  "Alberto: Y yo escribiendo pliegos. Qué palabra más horrorosa",
  "Xoana: Que es lo que hay que decirle a los niños hoy en día.",
  "Alberto: Qué guay tu curro Boque!",
  "Xoana: Yo de camino a la playa 😂 que es festivo",
  "Alberto: 💔",
  "Luigi: Muy guapo",
  "Luigi: Yo estoy pintando zocalos y ventanas",
  "Luigi: En un hôtel particulier de 150M de €",
  "Luigi: En Paris",
  "Boque: Ok a ver, estoy ahora viendo un video sobre Cambio Climático con los chavales y estoy viendo todo lo que habéis enviado",
  "Boque: Mirad, de lo que yo envié y, por ejemplo, el de 7 que ha enviado Xo, están bien, pero no están en el propio centro",
  "Boque: Están algo más alejados y es verdad que quizá, si no vamos a usar la piscina (en el caso de los que yo puse) o si tenemos luego que coger taxis para llegar a dormir, quizá lo suyo sea ir a huevo al centro (evitando calles de borrachos y andando lo justo posible para no estar en el meollo y poder dormir algo)",
  "Boque: Así que, en mi opinión lo mejor va a ser coger varios apartamentos en un mismo edificio o misma calle",
  "Boque: Este es el caso de los apartamentos de SunCity",
  "Boque: https://www.suncitymalaga.com/",
  "Boque: Yo estuve un tiempo trabajando en el departamento de reservas de esta gente hace unos años",
  "Boque: Alguno de los que ha puesto Ana y Xo son de esta gente, el de Calle Salitre",
  "Boque: Si os parece hablo con ellos y a ver si me hacen algo de precio (desde luego mejor que el de Booking, porque eliminaríamos la comisión) y me reservan con cancelación gratuita hasta una semana antes",
  "Xoana: Genial",
  "Xoana: Lo que te parezca",
  "Boque: Lo suyo sería, por ejemplo, pillar los dos apartamentos de calle salitre (4 y 4) o los dos de calle Victoria (4 y 4) o los dos de calle Gigantes (4 y 4)",
  "Boque: Todos están muy céntricos y sería acabar la farra e irse a dormir",
  "Boque: Incluso podemos reservar 3 de 4 (12 pax) y cancelar luego uno de ellos",
  "Boque: Por garantizarnos que si alguien más quiere venir tenga sitio",
  "Boque: Si os parece pregunto y os voy contando",
  "Alberto: A mí me parece bien",
  "Xoana: ¡Vale!",
  "Alberto: Dsbuten",
  "Alberto: O como se diga",
  "Boque: Ea",
  "Boque: Pues les llamo esta tarde y os digo",
  "Alberto: En Valencia se dice “estoy de acuerdo”",
  "Alberto: Ok! Gracias!",
  "Xoana: Aquí diríamos \"non reserves, maloserá\"",
  "Boque: jajaja",
  "Boque: Si reservamos estos tres apartamentos nos garantizamos 11 plazas (4 + 4 + 3) en la misma calle (dos de ellos en el mismo edificio)",
  "Boque: Por 846,50€",
  "Boque: salimos a 77€/testa",
  "Boque: Creo que podría conseguir que nos lo dejaran más bajo incluso",
  "Ana: Me parece estupendo",
  "Lolina: Está muy bien.",
  "Lolina: Me da pena no estar más juntos (que no revueltos)",
  "Boque: Ya, a mi también me molaba la idea de estar todos en uno solo",
  "Boque: Pero para eso nos tenemos que alejar más del centro",
  "Boque: Y al final ahí solo vamos a estar para dormir y ducharnos",
  "Boque: Porque hasta el desayuno lo tomaremos fuera",
  "Ana: Por eso",
  "Ana: Has dicho mismo edificio?",
  "Boque: Sí, creo recordar que los dos de Salitre I están en el mismo edificio",
  "Ana: Pues genial",
  "Boque: Llamo esta tarde y os digo, y si parece ya reservamos (puedo dar mi nº de tarjeta y luego ya arreglaremos vía bizum)",
  "Boque: Más que nada por garantizarnos algo y olvidarnos ya del tema",
  "Xoana: Perfecto",
  "Xoana: Muchas gracias",
  "Boque: Madre mía, se me acelera el corazón cuando lo pienso detenidamente 😅",
  "Boque: Vernos juntos otra vez",
  "Xoana: Jajaja",
  "Xoana: El túnel del tiempo",
  "Boque: Y si os parece correcto el planning que hice en el otro grupo, también organizo reservas en todos esos sitios que propuse",
  "Boque: Total",
  "Xoana: Guay. Si podemos colaborar con algo dinos. Si no, adelante.",
  "Alberto: Muchísimas gracias!",
  "Alberto: Igual me pillo una single para el resto de días o mejor por otra zona?",
  "Alberto: Ya no recuerdo bien por qué voy tantos días 😅",
  "Alberto: Eso",
  "Boque: A ver, no sé si te conviene más apartamento u hotel",
  "Boque: Lo que sea mas adecuado a tus necesidades y economía 😅",
  "Boque: Hay mil cosas que hacer aquí Albert",
  "Boque: No os preocupéis, os voy teniendo al tanto",
  "Boque: Mándame lo que vayas viendo y te digo cómo queda",
  "Boque: Amigos, he hablado con los que llevan los apartamentos y me recomiendan que coja los 2 de 4 mejores y luego otro de 4 (en total 12 plazas) pudiendo luego cancelar uno de ellos y nos quedamos con 8 plazas",
  "Boque: El total sería de 915 en vez de 847€",
  "Boque: Entre 12 el precio sería de 76,25€",
  "Boque: No, esto no es así",
  "Boque: Perdonad, estoy viendo tarifas no reembolsables",
  "Boque: Un segundo",
  "Boque: Que estoy con otras cosas y no me da",
  "Boque: 😅",
  "Alberto: Tranqui, sin prisas Boque",
  "Boque: Perdonad, ahora sí",
  "Boque: ‎Boque cambió la imagen de este grupo.",
  "Boque: A ver, el precio final en *tarifa cancelable a 7 días (hasta el 12 de abril a las 23:59)* de 3 apartamentos para 4 pax es de un total de *1011,50€*. Esto, si vamos 12, serían *84,30€ por cabeza.*",
  "Boque: Por favor, decidme en cuanto podáis porque corremos el riesgo de que los alquilen",
  "Boque: Le cambio el logo al grupo porque no soporto los grupos sin imagen 😅 ‎<Se editó este mensaje.>",
  "Boque: Disculpad porque todos los precios que había pasado esta mañana (antes del mensaje de las 15:35) eran en tarifa no reembolsable, y claro, bajan bastante respecto a los de cancelación flexible 🙃",
  "Ana: Yo por mi cogía la opción de los dos apartamentos de tarifa no reembolsable y el otro con la opción de cancelación",
  "Boque: Yo por mi también",
  "Boque: Es una forma de comprometernos definitivamente 😂",
  "Xoana: Por mí perfecto",
  "Lolina: Yo delego en Ana y Xoana",
  "Lolina: Lo mismo que ellas voten bien hecho está",
  "Alberto: Yo no estoy en absoluto de acuerdo. No sé, esperaba un poco más de búsqueda e ilusión",
  "Alberto: Algo cerca de la giralda o el pisuerga",
  "Alberto: O de Albacete",
  "Boque: Ok, a ver qué dice @33630328983",
  "Lolina: Que quiere el apartamento con vistas al acueducto",
  "Boque: Si él confirma entonces sí que somos 6 para los 2 apartamentos",
  "Luigi: Hola",
  "Luigi: No me he leido los 400 mensajes",
  "Luigi: Pero yo aún no puedo confirmar nada",
  "Boque: Ok",
  "Boque: Entonces pagamos los 2 apartamentos entre 5 en tarifa no reembolsable?",
  "Luigi: En cambio me fio completamente de vuestro criterio",
  "Luigi: (Mejor dicho de vuestra falta de…)",
  "Boque: Nos arriesgamos a que no venga nadie más y nos quedemos Alberto y yo en un apartamento de 4 y vosotras en el de 3 😅",
  "Boque: Cuando sabrás?",
  "Luigi: No lo sé aún",
  "Luigi: No se nada",
  "Luigi: Depende de mi curro",
  "Luigi: Pero yo creo que si iré",
  "Luigi: A 90%",
  "Boque: Otra opción es que pillemos uno de 2 para nosotros Albert y uno de 3 para vosotras chicas",
  "Luigi: Lo que aún no se es desde donde",
  "Boque: Y los demás que se busquen la vida",
  "Boque: 😂😂😂",
  "Luigi: Yo duermo con las chicas",
  "Luigi: Pero aún no se con cuáles",
  "Boque: No creo que tu mujer esté muy de acuerdo con esa frase 🤔😉",
  "Luigi: Cierto",
  "Boque: En fin, no sé, son muchas las opciones",
  "Boque: Si pillamos los 2 de 4 personas entre 5 salimos a *127,60€*",
  "Xoana: La diferencia entre pagarlo entre 5 o 6 igual tampoco es tanta",
  "Xoana: Y maloserá",
  "Xoana: 😂",
  "Boque: Ya, pero sin garantías de que alguien más se vaya a puntar",
  "Xoana: Que ni Luis o Laura puedan",
  "Boque: Me encanta esta expresión",
  "Boque: Hemos obviado la negativa de Alberto, por cierto 😂",
  "Xoana: Si pagarlo entre 5 nos sigue saliendo mejor que las tarifas con cancelación",
  "Xoana: Yo la veo claro",
  "Xoana: Lo cogería",
  "Boque: Sí, la flexible entre 5 por los 2 apartamentos es de *141,2€* ‎<Se editó este mensaje.>",
  "Boque: Ok, entonces",
  "Xoana: Venga, los dos de 4",
  "Boque: Ok",
  "Boque: en NR, no?",
  "Xoana: Tenemos margen para 3 personas más, que ya me parece un optimismo loco",
  "Xoana: Sí",
  "Xoana: Yo digo NR",
  "Luigi: Hay que tener Fe",
  "Boque: Pues entonces tenéis que hacerme un bizum de por ese importe",
  "Ana: Dalle",
  "Boque: *127,60€*",
  "Boque: Los reservo",
  "Lolina: Ok!",
  "Lolina: Yo confío en luis y laura",
  "Lolina: Y ya después reharemos los números",
  "Boque: Recibido Ana!",
  "Ana: 👍🏻",
  "Xoana: 😂",
  "Boque: Qué te gusta un disfraz 😂😂😂😂",
  "Luigi: Si te fijas bien en las fotos de Pisa, iba disfrazado todos los días",
  "Xoana: Yo sólo tengo fe en lo que me enseñó Tchit naht hanh",
  "Alberto: Yo no sé qué hostias decís. Me acabo de levantar de la siesta",
  "Alberto: Bizum a Boque de 127,6€ por el tema. Y lo de dormir?",
  "Luigi: Con tanto tema no creo que duermas",
  "Luigi: Podemos obviar ese gasto",
  "Luigi: Esa noche me quedé dormido caminando",
  "Luigi: Al despertar no sabía dónde estaba",
  "Luigi: No tenía batería en el móvil",
  "Luigi: Tuve que entrar en un hotel para que me dieran un plano tradicional en papel",
  "Luigi: Y tuve que volver a entrar para que me hiciera la Cruz de usted esta aquí",
  "Luigi: Todo por culpa de Alberto",
  "Boque: Agradeceré que los restantes, cuando podáis, hagáis el bizum, que si no me van a hacer un agujero muy majo en la cuenta 🙂",
  "Alberto: Jajajaja",
  "Alberto: ✅",
  "Boque: Recibido! Gracias!",
  "Lolina: Listo!",
  "Boque: Recibido Loles! Gracias!",
  "Alberto: Muchas gracias, Boque, espero que sea de calidad",
  "Boque: Por otra parte, reservamos uno en flexible cancelable por si acaso? O pasamos?",
  "Boque: Como dice Xo quizá sea soñar demasiado",
  "Lolina: Con estos cabemos 8?",
  "Boque: Sí",
  "Lolina: A mi ser más de 8 me parece utópico",
  "Lolina: Con laura y luis cuento, quizás ángel",
  "Boque: Loles, Ana, Xo, Laura, Alberto, Luis, Boque y Ángel",
  "Lolina: El resto no ha dicho ni mu, ni siquiera Jordi",
  "Lolina: Ah! Que no lo metimos en el grupo",
  "Boque: Quizá deberíamos comentarlo por el grupo para que la gente esté al tanto",
  "Boque: A lo mejor así se animan",
  "Luigi: X cierto , yo se lo comenté a las inglesas",
  "Boque: En serio?",
  "Luigi: Igual se pasan Lauren y Gemma",
  "Luigi: Siii",
  "Luigi: 😂",
  "Boque: Por qué?",
  "Lolina: Esas de apuntan a todo",
  "Luigi: Pero van a su aire",
  "Boque: Qué necesidad???",
  "Lolina: Jajajaj",
  "Luigi: Gemma vive allí",
  "Boque: Ya ya",
  "Boque: Si ella me encantaba",
  "Luigi: Cerca de Málaga",
  "Boque: Pero aun así no le veo mucho sentido",
  "Boque: A ver, para tomarnos unas copas va a dar igual en realidad",
  "Boque: 😂😂😂",
  "Luigi: No hay que buscarle sentido",
  "Luigi: Let it flow",
  "Luigi: Hay una piba en el metro que se está quedando dormida de pie",
  "Luigi: Debe haber estado de fiesta con @34659257878",
  "Alberto: Oye",
  "Luigi: Dime",
  "Alberto: Que me acabo de comer una manzana",
  "Luigi: Una al día keep the doctor s’est",
  "Luigi: Away",
  "Luigi: @34671447567 , nos vas a llevar al zz top?",
  "Xoana: Bizum hecho",
  "Boque: Recibido Xo!!!",
  "Boque: Gracias!!",
  "Boque: No creo",
  "Boque: Es el ZZ 😂",
  "Boque: Sin Top",
  "Boque: Ahí solo hay vicio y perdición",
  "Luigi: Mola mucho",
  "Xoana: ¿Es un sitio se topless?",
  "Luigi: Opcional",
  "Luigi: En verdad es un garitazo de rock",
  "Luigi: Yo he estado 2 veces y muy bien",
  "Luigi: Y ninguna de ellas el Boque se dignó a venir, dicho sea de paso",
  "Lolina: A ver si va a ser rollo el titty twister",
  "Boque: Es un sitio de musica en directo",
  "Boque: Conciertos de rock en plan a las 2:00 de la mañana",
  "Boque: Lo que pasa es que se pone imposible",
  "Xoana: A mí me vale todo.",
  "Boque: Yo siempre que llego hasta ese punto es porque la noche va a terminar muy mal",
  "Boque: Prefiero el Velvet",
  "Boque: Y el Copenhague",
  "Boque: Más civilizados",
  "Lolina: Yo pachanga",
  "Boque: Menos colas en los baños y menos problemas para pedir copas",
  "Lolina: Pa q mentir",
  "Boque: Si, una noche pachanga",
  "Boque: Pero otra indie",
  "Lolina: Me vale mucho",
  "Boque: Perfe",
  "Boque: Es que yo dos noches pachanga no puedo 😅",
  "Boque: No puedo ni una, pero sé que es lo que hay 😂😂😂",
  "Lolina: A ver pachanga de los 80",
  "Lolina: Ya por pedir",
  "Lolina: Me pones regueaton y me matas",
  "Boque: Eso es Velvet",
  "Boque: Ya ya",
  "Boque: Creo que el Velvet te va a molar mucho",
  "Boque: Te veo subida en un taburete al ritmo de Los Rodríguez y Manolo García 😝",
  "Boque: El Copenhague es más Fresones Rebeldes, Love of Lesbian, Izal, Lori Meyers, Sidonie, etc",
  "Ana: Perfecto",
  "Boque: Para esto el que es insuperable es el Indiana también",
  "Boque: Pero claro, el público medio ya ronda esa edad, de 45 para arriba 😅",
  "Boque: Ahí los jóvenes somos nosotros",
  "Boque: No veo el otro grupo muy animado, la verdad",
  "Boque: Creo que se acaba de crear una escisión importante 😂",
  "Luigi: No please",
  "Alberto: Pues a mí me gusta un poco, solo que no lo bailaría",
  "Alberto: En realidad me apetece mucho más estar charlando y bebiendo con vosotros. Lo de las discos siempre va al vertedero de mi memoria",
  "Alberto: Donde debería ir Izaly toda esa panda",
  "Alberto: Qué ganas de veros",
  "Boque: Esto es verdad",
  "Boque: Pero bueno, habrá tiempo para todo",
  "Boque: A mi llegado cierto momento lo único que me apetece es bailar",
  "Boque: Además creo que cada vez quedan menos sitios y oportunidades para hacerlo dignamente con estas edades 😂😂😂",
  "Boque: Así que hay que aprovechar 🕺🪩💃🏻",
  "Alberto: Jajajajaja odio bailar. Ojalá me gustase. Eso y creer en Dios. Ambas cosas liberadoras.",
  "Boque: 😂😂😂",
  "Boque: Me pasa igual con Dios",
  "Boque: Pero siempre nos quedará Miles Davis 🙏🏻",
  "Alberto: Está criando malvas, no?",
  "Boque: Desde hace años, sí",
  "Luigi: Whitney Houston le ayuda a regarlas",
  "Alberto: Joder, había comprado una entrada para ver en el teatro una movida de Jote de los planetas con Arrebato y otras cosas de Zulueta",
  "Alberto: A Xoana le hubiera encantado",
  "Xoana: A mí por dos días me da igual miles Davis o la gasolina",
  "Alberto: “Voz de ruido nevera” me dijo en 2004",
  "Xoana: Pero los planetas sí que no paso",
  "Xoana: Con vegetaciones",
  "Alberto: Esto lo hablamos paseando por el ponte di mezzo. También hablamos de Dragon Ball y de inteligencia artificial en juegos de estrategia.",
  "Xoana: Unos intelectuales",
  "Alberto: Ni yo por Izal. Y me voy a callar con vetusta morla porque sé que son prejuicios",
  "Alberto: A mí lo que me gusta es la gasolina y tener llenita la nevera. Y Pet Sounds",
  "Alberto: Oye, pues para tener 21 años y ser de Foios… hacía lo que podía. Tú te comprabas El País internacional. Yo Winston",
  "Xoana: Jajaja",
  "Xoana: Era todo mentira, en el medio metía la super pop",
  "Alberto: Jajaja",
  "Alberto: Vale, paremos, que nos van a pedir que hablemos por privado",
  "Xoana: Resumiendo, yo me fío 100% de lo que escoja @34671447567",
  "Alberto: Y yo",
  "Alberto: Y en realidad me da un poco igual",
  "Alberto: yo acabo de pillar la noche de jueves a viernes y de domingo a lunes (no les quedan para lunes a martes)",
  "Alberto: gracias, Boque!",
  "Boque: Aquí os paso unas fotos para ir abriendo boca 😄",
  "Luigi: Que bonito Granada!",
  "Boque: Ya quisieran los granainos tener playa",
  "Alberto: No tienes fotos de antros?",
  "Boque: Sí",
  "Boque: Las quieres?",
  "Alberto: Yo voy a ir a base de aguas",
  "Boque: Entre examen y examen corregido puedo ponerte alguna",
  "Alberto: Y no es coña",
  "Alberto: Pero me llevaré una petaquita con whisky para desinhibirme  un poco. Pero solo un poco",
  "Alberto: Eso son antros???",
  "Boque: El antiguo Bolivia",
  "Boque: Para las copas de la sobremesa",
  "Boque: Pero bueno, ya iremos viendo",
  "Boque: Organizaré el programa de actividades, pero luego me pondré en modo “let it flow”",
  "Boque: Y que sea lo que dios quiera",
  "Alberto: A mí me parece bien todo",
  "Alberto: De verdad",
  "Xoana: Iremos preparados para cualquier cosa.",
  "Xoana: Gracias y tampoco te estreses",
  "Boque: No me estreso, no te preocupes 😄",
  "Boque: Al revés, ojalá fuera ya este finde",
  "Xoana: ¡No! Para esto a nuestra edad ya hay que entrenar, como para el camino de Santiago",
  "Xoana: Yo hoy como con chupitos",
  "Boque: jajaja",
  "Boque: Vosotras las gallegas teneis un finde de aupa con las elecciones",
  "Xoana: Qué va, aquí todo funciona como un reloj",
  "Xoana: La reflexión está hecha",
  "Boque: Non o podo crer",
  "Xoana: Ahora a pasar el finde tranquilo",
  "Boque: Ea",
  "Boque: Pues no se hable mas",
  "Boque: A por unas zamburiñas y un ribeiro y que sea lo que el pueblo quiera",
  "Xoana: Joder, es que aquí la población está muy envejecida y se hace un lío.",
  "Boque: La verdad es que sí",
  "Xoana: Está muy bien que nos hagan una guía",
  "Xoana: A eso voy 😋",
  "Boque: Menos mal que hazteoir.org cuida de nuestra moral y nuestra ética, porque somos retrasados mentales y no tenemos capacidad para pensar y actuar de forma crítica y autónoma, nos lo tienen que venir a explicar ellos 🤔",
  "Xoana: Sí, me perturba más que el periódico más leído en Galicia publique esto hoy, diría que está prohibido.",
  "Xoana: Pero era una coña, me hizo gracia el formato.",
  "Xoana: Bien, regular, mal. 😂",
  "Boque: Pues eso, para retrasados mentales 😂",
  "Alberto: Derecho a la vida: ¿regular? Qué esconde eso? Falsa modestia o declaración de intenciones?",
  "Alberto: https://www.instagram.com/reel/C3ZteyECQEl/?igsh=MWtibHl6eXAwOGtv",
  "Alberto: Yo me quedaré aquí el resto de días.",
  "Alberto: https://maps.app.goo.gl/iNwFSuDWAk8bYe2u8?g_st=ic",
  "Boque: En Pedrega ❤️",
  "Boque: @34659257878, con mi colega Beto Casado, el otro de Pantomima",
  "Boque: Y yo con 6 kilos más 😂",
  "Boque: Hace 2 años justo antes del concierto de Nick Cave, en la zona vip",
  "Boque: O era Artic Monkeys? 🤔",
  "Boque: Da igual",
  "Boque: “rollo modernito indie” 😂",
  "Boque: “la sociedad de la nieve” 🤣",
  "Luigi: Rollo indie como las copas que se toma el bateria de los planetas?",
  "Alberto: Jajaja",
  "Luigi: https://youtu.be/nEVIeb8aH68?si=D0o1Ebh9eINiKH2F",
  "Alberto: Recuerdo que el poli me dijo: “Porti bombe in tasca? Viva Franco!”",
  "Alberto: Y creo que no se refería a Battiato",
  "Boque: 😂😂😂",
  "Alberto: Feliz domingo de erecciones",
  "Alberto: Espero que ejerzáis vuestro derecho",
  "Boque: Yo ejerzo mi derecho a la resaca hoy",
  "Boque: Ayer colocamos a los niños con los abuelos y salimos",
  "Boque: Así estaba a las 2 de la mañana",
  "Lolina: Hola",
  "Boque: 🐚",
  "Lolina: Llegué a mi casa a las 7:30",
  "Lolina: Tuvimos despedida de soltera",
  "Boque: No esperaba menos de ti Loles",
  "Lolina: Yo tampoco",
  "Boque: Eres una inspiración para este grupo",
  "Lolina: Nunca me quiero ir",
  "Boque: Marcas los tiempos",
  "Boque: Estas copas son por cierto en esta terraza",
  "Boque: La incluyo en el programa de actividades",
  "Boque: El bar de la 7ª planta de La Equitativa",
  "Boque: Todo con aires retro de los años 20",
  "Alberto: De esto habla muy bien ermesto sevilla",
  "Boque: Ernesto Sevilla habla bien de cualquier cosa",
  "Boque: Ernesto Sevilla presidente!",
  "Alberto: https://www.tiktok.com/@esdlb/video/7078316332017585413",
  "Alberto: Se puede ver sin app",
  "Alberto: Yo me he sentido así durante mucho tiempo. Ahora ya no. Pero la cabra, de vez en cuando, tira al monte, aunque sea en París ‎<Se editó este mensaje.>",
  "Luigi: Es muy probable que si que me apunte",
  "Luigi: Seguramente vaya desde Madrid",
  "Luigi: Igual en coche",
  "Luigi: O en ave, ya veré",
  "Xoana: ¡Genial! No esperábamos otra cosa",
  "Lolina: Luis!!!!🎉🎉🎉🎉",
  "Alberto: Bieeeeeennnn",
  "Alberto: Hurra!!",
  "Alberto: En ave, hombre, que como te tengas que volver en las condiciones que acabamos en parís",
  "Alberto: Volverías domingo o lunes?",
  "Alberto: Por hacerte hueco en mi jergón",
  "Luigi: Igual lunes cuando pase la marea",
  "Alberto: Algún sitio cerca de santiago?",
  "Alberto: No sé si casa rural en espacio natural. Nunca he probado balneario o similar",
  "Alberto: Quiero: leer, pasear y descansar",
  "Luigi: Vete a un monasterio",
  "Alberto: Lo había pensado",
  "Alberto: Pero paso de esos horarios",
  "Alberto: O sea, no me quiero integrar",
  "Alberto: Quiero ir a mi bola",
  "Alberto: (Perdonad el inciso)",
  "Boque: Vamos!!!! 👏🏻👏🏻👏🏻",
  "Alberto: Joder, igual hago Santiago (sin compromiso, chicas) y Lille (Luigi) en marzo y en abril Málaga (todos). Vaya movida",
  "Alberto: Parece que me queden meses de vida",
  "Boque: 😂😂😂",
  "Boque: Deberías enganchar con el Escorial entre Santiago y Málaga 😂",
  "Alberto: Y ni así conseguiría ver a Jordi",
  "Boque: Galleguiñas, a qué hora llegaréis entonces a Málaga del Caminito del Rey?",
  "Boque: Alberto, tú vas con ellas o estarás por Málaga?",
  "Boque: Y tu Luighi? Sabes sobre qué hora llegarías?",
  "Ana: Yo al caminito casi fijo no voy",
  "Boque: En el apartamento se entra a las 14:00",
  "Ana: Me instalaré en una cafetería y si estáis todos ocupados trabajaré un rato",
  "Boque: Lo digo porque a efectos de logística para reservar para comer y demás interesa saber si podréis dejar las maletas en los apartamentos o iréis con ellas a comer",
  "Boque: Yo salgo a las 14:45, pero mi mujer me acerca con el coche",
  "Boque: Yo sí que iré con la maleta (o mochila o lo que sea) porque ir al apartamento y volver es una pérdida de tiempo",
  "Boque: Ok",
  "Luigi: Ok a todo menos a currar",
  "Luigi: Aunque sea leer el Hola es ya un mejor plan",
  "Ana: Bueno... en realidad era lo que iba a hacer... pero me pareció mejor decir que iba a trabajar...",
  "Luigi: Si puedo me uno",
  "Lolina: Oye!",
  "Lolina: El pueblo donde estuvimos enfrente de capri cómo se llamaba?",
  "Lolina: Sorrento?",
  "Boque: Enfrente de Capri está Sorrento, sí",
  "Lolina: Y nosotros estuvimos allí???",
  "Boque: Limones por todos lados",
  "Boque: Yo estuve pero por mi cuenta, cuando acabe el curso y me fui dos meses con el coche en verano hasta Sicilia",
  "Boque: En cualquier caso creo que si hubiera estado contigo quizá tampoco me acordaría 😂",
  "Xoana: 😂",
  "Xoana: Sí, Sorrento",
  "Lolina: Ok!",
  "Alberto: Sí, os fuisteis a una disco del pueblo y yo me quedé en la tienda de campaña.",
  "Alberto: quedamos, Ana? Yo estaré desde el día anterior",
  "Ana: Claro!",
  "Alberto: Haremos nuestro propio caminito",
  "Ana: Te espero en el bar... porque cuando lleguemos estarás durmiendo fijo",
  "Ana: Jajaja",
  "Alberto: 🍻",
  "Boque: Os recomiendo sitios si queréis para echar la mañana",
  "Alberto: Claro",
  "Alberto: Pero mejor cuando se acerque el día porque yo no recuerdo ya nada de lo que hemos hablado por aquí",
  "Alberto: Algo de la mensa y Lolo, no?",
  "Alberto: Y no sé qué selfies y pepinos",
  "Alberto: Nuestro manager. Ya nunca dijo nada más. Un buen mensaje de despedida.",
  "Alberto: Au revoir",
  "Boque: Estos soliloquios tan tuyos me encantan Albert",
  "Boque: Acabo de encender la TV tras acostar a los niños y veo que la cosa está que arde por Valencia, no?",
  "Boque: Parece que al menos no hay fallecidos",
  "Boque: Esperemos que solo quede en daños materiales",
  "Boque: Madre mía, lo estoy viendo bien ahora y es un edificio inmenso, no???",
  "Boque: Espero que no haya fallecidos ni heridos graves 🙏🏻",
  "Boque: En otro orden de cosas (especialmente para Albert y Luighi), acabo de terminar de verme este docu y me ha molado todo ‎<Se editó este mensaje.>",
  "Boque: La historia de la composición y grabación del Échate un Cantecito de Kiko Veneno",
  "Boque: Un paseo por la Sevilla de los 80 con Raimundo, Santiago Auseron, Ricardo Pachon, etc",
  "Boque: Si tenéis oportunidad, vedlo 👈🏻",
  "Lolina: En qué plataforma?",
  "Boque: En Movistar lo he visto yo",
  "Lolina: 👍🏻",
  "Alberto: Ha sido jodido, conozco a una chica de edificio colindante y casi me da algo hasta que me ha dicho que estaba bien.",
  "Alberto: Bona nit",
  "Xoana: Qué animalada, no había visto nada",
  "Luigi: Cool",
  "Alberto: Lo tengo pendiente",
  "Alberto: Te lo cambio por este:",
  "Alberto: https://m.filmaffinity.com/es/film198667.html",
  "Boque: Interesante",
  "Boque: 📝",
  "Boque: Acabo de ver en las noticias que hay 4 fallecidos y 19 desaparecidos 😢",
  "Boque: Menuda tragedia",
  "Boque: Ánimo a los nanos y nanas levantinos",
  "Alberto: Tuve que apagar la tele. No tenía sentido retransmitir eso en directo. Hay entre los desparecidos gente conocida de mi entorno. Sí, una puta tragedia",
  "Luigi: Que horror",
  "Luigi: Ánimo Alber",
  "Alberto: Gracias. Tranqui. Yo estaba muy preocupado por una persona muy importante para mí que solo me ha dicho “estoy bien”. Nada más. Del edificio de al lado. Reconocí el que se ha quemado porque he pasado por ahí mil veces para entrar en su casa. Claro, cuando empecé a ver las imágenes ya de por sí jodidas, tuve que salir para ver cuál era la dirección del viento porque me temí lo peor. Solo hay 20m de distancia ‎<Se editó este mensaje.>",
  "Alberto: En fin. Tragedias de la vida. Retransmitidas en directo de una forma muy chunga, en apunt parecía que solo estaba en riesgo el padre y su hija del balcón (aunque entiendo que es difícil hacerlo de otra manera).",
  "Boque: Madre mía, mucho ánimo",
  "Luigi: Por eso hay que juntarse más, no sabemos cuando nos van a cortar el hilo",
  "Alberto: Tal cual",
  "Luigi: Ánimo y a por el finde",
  "Alberto: Llevo pensando así mucho tiempo. Y hay que intentar pensar en ello sin dramas. Se cortará el hilo y a saber en qué nos convertimos. Yo creo que en compost.",
  "Luigi: En compost seguro",
  "Luigi: Y luego en otras cosas",
  "Alberto: Son varias canciones, todas hechas a partir de Cosmos, mi serie favorita",
  "Alberto: Os comparto la que más me gusta. Luigi y Xo ya la conocen",
  "Alberto: https://youtu.be/XGK84Poeynk?si=InSBYq_xq1wFYg3w",
  "Alberto: En el minuto 2 siempre se me ponen los pelos de punta. Neil deGrasse Tyson 💙",
  "Xoana: Conmigo contad siempre. Tengo muy interiorizado lo de que me corten la luz en cualquier momento",
  "Xoana: https://youtu.be/ziJuNQcJn24?feature=shared",
  "Boque: Crecí mamando esto",
  "Boque: Tengo varios libros de este hombre además",
  "Boque: Yo, por desgracia, también",
  "Boque: Y el mejor ejercicio para llevar esto a la práctica es levantarse cada mañana y al mirarse al espejo despues de lavarse la cara, pensar que hay que vivir cada día como si fuera el último",
  "Boque: Para los que tenemos hijos además esto cobra un significado más profundo, porque morirse uno, como que da igual",
  "Boque: Lo único que te preocupa es lo que dejas en este mundo",
  "Boque: En fin, ánimo y a por el finde, sí",
  "Boque: Yo me voy de casa rural con mis suegros 😭😭😭",
  "Alberto: O como si fuera el primero, con la posibilidad de que sea el último",
  "Alberto: Que si no no te vas a plantear nunca nada a largo plazo!",
  "Alberto: Paso de emprender este proyecto, son 3 años y a saber. Mamá, saca el mdma y el jack daniels.",
  "Boque: jajaja",
  "Alberto: Y tampoco es eso!",
  "Boque: cómo te gusta sacar de quicio las cosas 😂",
  "Alberto: Las pongo en otro quicio, en el mío, con mis bisagras. En fin, como unas maracas estoy",
  "Xoana: Con los coches aprendiste a pensar a largo plazo",
  "Boque: 😂",
  "Alberto: Jajajajaj",
  "Boque: Lo que dijo @34650544830, de eso nada más que salieron cosas buenas 😂😂😂",
  "Boque: Bueno, os dejo que me pongo a corregir",
  "Alberto: Bueno, a mí me salieron muchos granos",
  "Alberto: Y creo que pasé por una mini depresión en Pisa. Y empecé a leer. Gracias a Luigi: las partículas elementales me llevaron a 1984 y Un mundo feliz y luego ya todo lo demás hasta ahora: mortadelo y filemón ‎<Se editó este mensaje.>",
  "Alberto: También descubrí a Calvin y Hobbes y me interesé por Umberto Eco gracias a dos personas aquí presentes",
  "Alberto: También flipé con que me describieran a Xoana como una chica muy inteligente, superdotada, porque leía libros como El código da Vinci 😂",
  "Alberto: “Libros raros” recuerdo que me dijo alguien",
  "Alberto: Salió ese año. Superventas total",
  "Boque: Umberto Eco ❤️",
  "Boque: El Péndulo de Foucault 🙏🏻",
  "Alberto: Justo, os oí hablar a Jordi y a ti",
  "Alberto: Era todo oídos. Yo solo sabía la diferencia de precio entre Fortuna y Winston. Y algo de música. Aprendí un huevo con vosotros.",
  "Boque: Y nosotros contigo ❤️",
  "Boque: Y ahora dejemos de chuparnos las pollas y trabajemos un poco",
  "Alberto: Jajajaja, qué va! Ahí salí ganando yo",
  "Alberto: Soez",
  "Boque: Que cuando empiezas con la diarrea verbal no paras 😂😂😂",
  "Alberto: Lo sé.",
  "Alberto: Uy",
  "Alberto: 🤐",
  "Boque: 😂",
  "Boque: Que no hombre, que no",
  "Boque: Para eso está whatsapp",
  "Alberto: 🤐🤐🤐🤐",
  "Boque: Para escribir todo lo que quieras",
  "Boque: Que ya te echará alguien del grupo",
  "Alberto: 🥺",
  "Alberto: 🤐",
  "Boque: jajaja",
  "Boque: A mi porque me pillas de guardia y estoy en la sala de profes corrigiendo (sin gana alguna)",
  "Boque: Que si no no estaría aquí dándote palique",
  "Alberto: Lo último: aquí único depositario de las chapas tanto tuyas como de jordi fui yo",
  "Boque: True",
  "Alberto: Y eran unidireccionales",
  "Alberto: Esta foto lo resume todo",
  "Xoana: Lo de libros raros sería Edu que le dejé una joya de Asimov que no recuperé 😂",
  "Boque: La usaría para calzar algun mueble",
  "Xoana: Seguro",
  "Alberto: O para calzarse a alguien diciendo que leía",
  "Xoana: Sí",
  "Xoana: Fue al principio, aún no sabía por donde tirar",
  "Xoana: 😂",
  "Boque: 😂",
  "Boque: Familia, respecto a la comida del viernes: si quedamos a las 15:15 en Pedregalejo (zona este de la ciudad), os dará tiempo a dejar las maletas a las 14:00 en los apartamentos (zona oeste de la ciudad)? ‎<Se editó este mensaje.>",
  "Boque: Lo digo por las que vais al Caminito, que Albert y Ana supongo que no tendrán problema",
  "Boque: Para que no vengáis con las maletas",
  "Boque: A mi me suelta mi mujer allí e iré con la maleta, la idea es comer en Pedrega y luego tomar las copas en el Balneario para luego ir a los apartamentos, ducharnos o descansar un poco antes de volver a echarnos a las calles para cenar y salir",
  "Boque: Otra opción es que el viernes comamos en el centro y el sábado hagamos el plan de Pedrega y Balneario",
  "Boque: Invertir el orden",
  "Xoana: Sí, hemos decidido dejar el caminito para después del verano, porque ese día nos levantamos muy temprano y no queremos condicionar el día",
  "Xoana: Cómo tú digas",
  "Boque: El sábado yo creo que nos dará mas pereza movernos a Pedrega",
  "Boque: Así que nada, se mantiene el programa",
  "Boque: Llamaré en unas semanas para reservar todo",
  "Xoana: Guay",
  "Alberto: Muchas gracias, Boque",
  "Alberto: Yo voy en plan follow the leader",
  "Boque: Otra cosa, para garantizarnos sitio en alguna terraza lo mismo nos piden que reservemos al menos una botella (algo bastante común). De una botella, en circunstancias normales, deberían salir unas 10 copas, por lo que el precio al final suele ser igual al de pedirlas. Pero claro, el problema es, *¿de qué se pide la botella?*",
  "Boque: Sois más de ron, de whisky, ginebra???",
  "Boque: O pasamos de reservar mesa y en vez de ir como unos señores y señoras nos peleamos con la juventud para pillar un sitio decente cada vez que lleguemos a una terraza",
  "Ana: Ron o ginebra me valen",
  "Boque: Yo voy por el gin también",
  "Boque: ‎ENCUESTA:",
  "Boque: Va a ser más fácil así",
  "Xoana: Yo todo menos whisky",
  "Boque: Eres una todoterreno Xo 😄",
  "Xoana: Jajaja",
  "Xoana: Soy una persona tolerante",
  "Lolina: Llegado el caso yo como Xoana!",
  "Lolina: El tequila se me haría duro, pero hemos venido a jugar",
  "Alberto: Yo whisky menos todo",
  "Alberto: Pero Luigi y yo vamos a llevar sendas petacas llenas de uno japonés ahumado que voy a llevar.",
  "Alberto: Yo beberé eso y agua con hielos",
  "Luigi: Yo colacao",
  "Alberto: Rollo indie",
  "Lolina: Yo eso ya lo vi",
  "Lolina: Y con magdalenas",
  "Alberto: Como en París",
  "Boque: Yo le hago a todo",
  "Xoana: Yo que creía que lo del whisky japonés era sólo una manía de un colega",
  "Xoana: Ya no me voy a meter con él.",
  "Boque: Los whiskys (y las ginebras) japos son la caña",
  "Alberto: Yo lo he probado pocas veces. Sobre todo he bebido jack, para evitar el gas de la cerveza y los refrescos de las copas, pero lo bebo a la misma velocidad y claro",
  "Luigi: El whisky con agua es una trampa mortal",
  "Luigi: Sin gas , te los crujes como zumo de manzana",
  "Alberto: No, no, si yo no los mezclo",
  "Alberto: El agua aparte",
  "Boque: Luighi tú yo tenemos pendiente bajarnos una buena botella de whisky viendo Beautiful Girls",
  "Boque: Y lo sabes",
  "Luigi: Sweet Caroline",
  "Alberto: Bueno, bueno, aparataditos",
  "Alberto: Pues yo con las chicas",
  "Boque: Estás más que invitado Albert",
  "Boque: Y las chicas también",
  "Boque: Pero entonces tendrán que ser más botellas",
  "Alberto: Podemos ir, chicas. El leader nos deja.",
  "Alberto: Yo llevaré una.",
  "Alberto: Bueno, no, la compro allí, que voy en avión",
  "Boque: Follow the leader leader leader, follow the leader, sígueme!",
  "Boque: En Málaga vamos siempre un paso por delante 😂",
  "Lolina: 😂😂😂😂",
  "Lolina: Especialmente los domingos",
  "Boque: Algunos colegas míos van a Madrid a verlos",
  "Boque: Los solteros sin hijos para ser más precisos ‎<Se editó este mensaje.>",
  "Xoana: Esta gente nos va a sobrevivir",
  "Xoana: Hace 20 años ya parecía que les quedaba poco",
  "Luigi: 😂😂😂",
  "Xoana: Jajaja",
  "Ángel: ‎Boque añadió a Ángel.",
  "Boque: Venga, que Angelo se viene 👏🏻👏🏻👏🏻",
  "Lolina: Yuhuuuu",
  "Luigi: Vamoooooos",
  "Xoana: 🥳🥳🥳",
  "Alberto: Toma ya!",
  "Luigi: Canasta!",
  "Luigi: Ha confirmado?",
  "Boque: He tenido una conversación telefónica muy seria con él",
  "Alberto: Unas risas muy serias",
  "Boque: Y como parte de la estrategia de presión he decidido meterle aquí 😂",
  "Boque: Eso mismo",
  "Ana: 🙌🏼🙌🏼🙌🏼🙌🏼",
  "Ángel: 🤣🤣🤣🤣",
  "Ángel: Que cabron..",
  "Lolina: Mete a Jordi",
  "Lolina: 😂😂😂😂😂",
  "Xoana: Jajaja",
  "Boque: 😂😂😂",
  "Luigi: Vamoooosss nano",
  "Boque: Empiezo a mover hilos 😄",
  "Xoana: Boque, te queremos",
  "Xoana: Loles alcaldesa, tú embajador",
  "Boque: Yo os quiero más",
  "Alberto: Jolín, muchas gracias",
  "Ángel: Ehh que mi avión llega a las 15:45..🤣🤣🤣",
  "Boque: Qué dices! Ya tienes billetes????",
  "Xoana: Tráete bocata",
  "Ángel: 😔😡",
  "Xoana: 😂😂",
  "Boque: Pero tienes billetes o no??? Si llegas a esa hora no te preocupes, te esperamos allí con las copas Angelo 😉",
  "Ángel: Buenos días.. no lo he comprado, pero ya esta mirado, mi idea es comprarlo cuando lo compre Luigi!!",
  "Alberto: Joder, bordas la estrategia: nostalgia y chantaje!",
  "Alberto: Venga, que tengo muchas ganas de veros.",
  "Luigi: Yo estoy confirmado ya a 100 %",
  "Luigi: Este finde lo compro",
  "Alberto: @34669656647 ya tienes faena",
  "Alberto: https://youtu.be/3nxXrHZ2HL4?si=LU8g30srJl0EzEyz",
  "Alberto: Tenemos que ensayar el baile de Battiato. Quizás venga la policía. Otra vez",
  "Alberto: https://youtu.be/tGhG7gTG-Os?si=KymZeVA3fIdx3ruM",
  "Alberto: (Para Ángel, que es el único que aprendió menos italiano que yo)",
  "Alberto: (Pero, en cambio, ya sabía latín cuando llegamos a Pisa)",
  "Ángel: Esta semana ejecutó..",
  "Boque: Ángel, no sé a cuánto te sale el billete, pero quizá el ave te salga más a cuenta",
  "Boque: Vuelta",
  "Boque: Se te pone en 160€",
  "Boque: Y es verdad que son 5 horas",
  "Boque: Pero sales del centro de Valencia y llegas al centro de Málaga",
  "Boque: Y a unas horas cojonudas",
  "Boque: Que entre que llegas al aeropuerto, pasas control, embarcas, etc. al final es igual que el tren",
  "Alberto: Cuando lo vi yo, 80€ i/v",
  "Boque: Entonces no hay duda",
  "Boque: Ahora, si el billete está por 140€ yo me lo plantearía 🤔",
  "Alberto: Cómo se nota que eres el líder",
  "Alberto: Haces las cuentas en milisegundos",
  "Ángel: Ayer eran 120€",
  "Ángel: Pero son 2 horas ..no 5..",
  "Alberto: A mí me suena también q hay que pasar por Madrid",
  "Alberto: En todo caso, yo iría en tren por todo lo que dice boque",
  "Ángel: Si no facturo llego 20 minutos antes..y cuando llegue taxi directo a la comida",
  "Boque: Llegarías demasiado pronto 😂",
  "Boque: Yo salgo a las 14:45 de currar",
  "Boque: Llegaré a la 15:15",
  "Lolina: Llega perfecto",
  "Lolina: Para el aperitivo",
  "Boque: Yo iría al apartamento a las 14:00 a dejar maletas y recoger llaves y de ahí a comer 😅",
  "Boque: Las llaves cuanto antes se pillen, mejor",
  "Boque: Porque luego estarán repartiendo llaves por toda la ciudad a los cientos de turistas que lleguen ese finde",
  "Boque: Pero está también es buena opción: del tirón con la maleta",
  "Ángel: Me veo toda la tarde-noche..dencopas con la maleta..🤦🏻‍♂️",
  "Boque: No way",
  "Boque: Del balneario en todo caso vamos al Titi a tomar una y de ahí a los apartamentos",
  "Boque: No estoy dispuesto a ir con la maleta por Málaga como los guiris 😂",
  "Alberto: Para Ana",
  "Boque: 😂😂😂",
  "Boque: Captcha",
  "Xoana: Jajaja",
  "Luigi: 😂",
  "Luigi: Que captcha colega!",
  "Ana: Jajaja",
  "Boque: Nano, tienes el billete ya???",
  "Boque: Y tu Luighi???",
  "Luigi: No pero me ocupo esta semana",
  "Ángel: Hasta que no vea  oos de Luigi no ejecuo",
  "Boque: 😂",
  "Boque: Vaya dos",
  "Boque: https://reloj-alarma.es/temporizador/Erasmus+2024/2024-04-19T01:00:00/",
  "Boque: Meto este temporizador inverso en la descripción",
  "Boque: (la descripción del grupo)",
  "Boque: Para que vayamos haciendo ganas",
  "Boque: ‎Boque cambió la descripción del grupo.",
  "Xoana: Haces bien, ya me estaba notando desmotivada",
  "Xoana: 😂",
  "Boque: jajaja",
  "Boque: He contemplado la posibilidad de alquilar un catamarán y que nos lleve a dar una vuelta por la bahía de Málaga al atardecer para tomarnos unas copas",
  "Boque: Pero después he pensado que es perder mucho tiempo y dispara el presupuesto",
  "Boque: A ver, si vinierais para 5 días, pues sí",
  "Boque: Pero es que esto va a ser una _tour de force_",
  "Boque: Como una boda",
  "Boque: Cuando queramos darnos cuenta se ha acabado 😢",
  "Xoana: A mí todo me parece bien y buena inversión, así que lo que te parezca.",
  "Xoana: No me importa hacer un esfuerzo en mis finanzas si es para algo distinto.",
  "Boque: Ya, yo pienso igual",
  "Boque: Pero es que entre que llegamos al muelle, salimos, damos la vuelta, volvemos con la moña en lo alto, desembarcamos y demás se dispersa mucho la cosa",
  "Xoana: Correcto",
  "Ángel: Barco nooo",
  "Alberto: Yo poto seguro",
  "Alberto: Pero puedo tomar una biodramina",
  "Alberto: Rollo indie",
  "Boque: Nada nada",
  "Boque: Nos quedamos en tierra",
  "Boque: Y si tenemos que marearnos que sea por culpa del Jaggermeister",
  "Alberto: Puajjj, tendré que tomar drogas entonces",
  "Boque: Drogas are welcome",
  "Boque: En su justa medida",
  "Boque: Y casi como un guiño a la nostalgia",
  "Boque: Además Xo ha dicho esto",
  "Boque: Así que hay carta blanca",
  "Boque: y nunca mejor dicho 😂",
  "Boque: Perdonad, que estoy corrigiendo exámenes y me da un poco vueltas la cabeza y ya digo cualquier tontería que se me pasa por la cabeza",
  "Boque: Bueno, exámenes no, productos finales de las situaciones de aprendizaje 😌",
  "Xoana: Jajaja",
  "Boque: Los que no tenéis billete no podéis opinar hasta que no confirméis asistencia",
  "Xoana: Correcto",
  "Xoana: A mí el jaggermeister me vale también",
  "Boque: Estoy haciendo movimientos y pidiendo favores para poder escaquearme el viernes a ultima hora y llegar sobre las 14:30 al restaurante y no a las 15:30",
  "Boque: Y una cosa importante: traeos el bikini/bañador!",
  "Ángel: En que franja horaria tenemos tiempo para bañador?",
  "Ángel: Meter a Laura en el grupo...para presionar!!",
  "Xoana: Jajaja",
  "Xoana: Sí, ella quiere venir pero depende del curro y no lo sabrá hasta el final. Si fuese por ella ya tendría los billetes.",
  "Boque: Metámosla!!!",
  "Boque: Aunque ahora que estamos hablando de drogas quizá mejor no hacerlo 😂",
  "Boque: La mañana del sábado y la del domingo",
  "Boque: Bañito en la playa después de desayunar, que despeja",
  "Ángel: Hable con ella...me lo comentó.. pero me pareció entender que el viernes ( no se de que semana 🤷🏻‍♂️🤦🏻‍♂️) ya lo sabría!!",
  "Boque: Y luego del tirón a tomar unas cañas/vinos",
  "Boque: Pero no es realista, la verdad",
  "Ángel: 🤣🤣🤣..",
  "Boque: Además la playa que tenemos frente los apartamentos no es muy buena",
  "Boque: Pero nunca se sabe",
  "Xoana: Me veo sola en la playa",
  "Xoana: Yo el bañador lo llevo siempre",
  "Ángel: Noo...ya tenemos taitantos...no son los 24 de  la epoca",
  "Boque: Pero si tu vas a estar de resaca como todos 😂😂😂",
  "Xoana: No he tenido una resaca en mi vida",
  "Xoana: Jajaja",
  "Boque: A ver, yo para celebrar mi cumple todos los años me metía en el mar en pelotas el 7 de enero",
  "Boque: con eso lo dejo tdo dicho",
  "Xoana: Yo me meto 31 y 1 de enero",
  "Ángel: Boque..al examen de  Martinez ponle un 10!!",
  "Boque: Y en mi juventud (léase: hasta que tuve hijos) era muy de irme a la playa a las 5 de la mañana a despejarme con un baño fresquito",
  "Ángel: Alberto tiene que estar viendo fallas..no dice nada!!",
  "Xoana: La democracia es...",
  "Xoana: Normal que te tires al alcohol",
  "Boque: Ahora estoy preparando una prueba para los de 1º sobre la antigua Grecia y acabo de terminarme un vino, no queda otra",
  "Boque: jajaja",
  "Boque: ya ves",
  "Boque: Ya ves, con la diarrea verbal que suele tener 😂😂😂",
  "Ángel: Cuanta mentira le contamos a la juventud!!",
  "Alberto: Yo también, el resto del año solo alcohol",
  "Alberto: Xoana, somos como agapornis",
  "Laura: ‎Ana añadió a Laura.",
  "Luigi: Ya tengo billete de avión",
  "Lolina: Yuhuuuu",
  "Luigi: Ahora me falta el ave a magala",
  "Luigi: Nano dale caña",
  "Lolina: A ver Laura…",
  "Boque: Meted a Laura en el grupo!!",
  "Boque: Lauraaaaaaaaaaaaa ❤️❤️❤️",
  "Boque: Qué alegría que vayas a venir 👏🏻👏🏻👏🏻",
  "Laura: Yes of course",
  "Laura: Ya no m acuerdo d fechas",
  "Laura: 🤣🤣🤣",
  "Luigi: Olé",
  "Alberto: Bieeen!",
  "Laura: A ver... q tengo q pillar ave",
  "Laura: Decirme fecha",
  "Xoana: 19/04/24",
  "Laura: 👍🏼",
  "Laura: Hasta 22?",
  "Laura: O domingo vta?",
  "Laura: Viernes no puedo pillar pero lunes si",
  "Ana: Nosotras volvemos el domingo",
  "Laura: Y el viernes viajáis de mañana?",
  "Ana: Si",
  "Laura: Entonces tengo q negociar 🤣",
  "Ana: Jajaja",
  "Laura: Darme hasta mama",
  "Laura: Mana",
  "Laura: Mañana",
  "Ana: Claro!",
  "Laura: Pero recordármelo q se m va la olla",
  "Laura: Jajajajajajajajaja",
  "Lolina: Ponemos malaga el viernes",
  "Xoana: ¿Metemos a tu jefe en el chat?",
  "Laura: No jodas q tengo muchos y encima nuevos",
  "Laura: 🤣🤣🤣🤣",
  "Laura: A ver si m van a conocer antes d tiempo...",
  "Boque: Vamos Lau!",
  "Boque: Que ese viernes quemamos Málaga y el sábado la reconstruimos para volver a echarla abajo 🔥🔥🔥",
  "Boque: Tienes que hacer por llegar para estar el viernes a comer",
  "Luigi: Me duele la cabeza ya",
  "Luigi: Ya tengo el billete de tren",
  "Luigi: Nano estás tardando",
  "Alberto: Estamos hidratándonos",
  "Ana: Pero vosotros trabajáis en algún momento?",
  "Ángel: Pero estis en valencia?",
  "Alberto: Estamos en Bruselas",
  "Alberto: Uno no hace nada y el otro lo pasa a limpio",
  "Luigi: Pero estáis tontos?",
  "Luigi: Nano saca el billete",
  "Boque: Vaya pintas 😂",
  "Luigi: Un vagata",
  "Boque: Un crack, como siempre ❤️",
  "Boque: De mayor quiero ser como tu 😉",
  "Luigi: Leyéndome un cómic de jodorsky y moebius",
  "Luigi: Tu llevas siendo mayor desde que estábamos en Pisa",
  "Luigi: 😍😘",
  "Boque: El INCAL!",
  "Luigi: Exacto",
  "Ángel: Y a mi..tengo resaca de leeros!!",
  "Luigi: Paracetamol preventivo",
  "Xoana: Yo creyendo que guardaba un Bitcoin y Luis leyendo libros con dibujitos",
  "Luigi: Que grande",
  "Luigi: Mis inicios en el street art",
  "Ángel: 🕺🏻🕺🏻",
  "Luigi: Angel ya tienes los billetes?",
  "Ángel: Hasta que no los tenga Laura yo no saco nada..",
  "Laura: Estoy en ello vale?",
  "Laura: Jajajajajajjaja",
  "Laura: Es q estoy pensando en madrugar el viernes o irme el jueves d tarde 🤔",
  "Ángel: Alberto llega el jueves...🤷🏻‍♂️🤷🏻‍♂️..",
  "Luigi: A ti no te hace falta billete, tu vienes corriendo",
  "Luigi: Es Increible, todo el rato hablando de billetes y nadie hace la broma facil…",
  "Luigi: Como hemos cambiado…",
  "Xoana: Qué lejos ha quedado",
  "Luigi: Presuntos implicados",
  "Xoana: 🙃",
  "Laura: Llego el jueves",
  "Ángel: 👏🏻👏🏻👏🏻👏🏻",
  "Boque: Temazo de Presuntos!!!!!!",
  "Boque: Ah, llego tarde 😂",
  "Boque: Wooooooo 🙌🏻🙌🏻🙌🏻",
  "Boque: Estoy por pedirme el viernes 😂",
  "Xoana: Los profesores no podéis pedir días",
  "Xoana: 😂",
  "Laura: Y una mierd",
  "Xoana: Por eso vamos a Málaga jajaja",
  "Laura: Q yo tb soy profa",
  "Laura: 🤣🤣🤣🤣",
  "Luigi: Vamos y’a boque Ron!",
  "Boque: Mae mia soy un viejo 😅😭😝",
  "Xoana: Tranqui",
  "Xoana: Espera a vernos a los demás",
  "Ángel: 🤣🤣🤣🤣",
  "Ángel: Mete a Edu en el grupo que se me acaban las escusas.. 🤣🤣",
  "Laura: Jajajajajajajajajjaja",
  "Ángel: Boque..que digo yo..que con esto que seas organizando el finde te estás pegando una farra para ir reservando que no veas!!",
  "Boque: Quita quita 😂",
  "Boque: Que nos revienta el grupo 😂",
  "Xoana: Como siga así va a acabar encontrándose con Edu en algún garito",
  "Luigi: Chicos",
  "Luigi: A quien tengo que pagar el alohamiento?",
  "Xoana: El alojamiento está pagado entre 5, para no recalcular y montar un casino lo más práctico sería que tú, Laura y ángel pongáis la misma cantidad y lo usemos de bote para pagar cenas y comidas?",
  "Luigi: Me parece una idea cojonuda",
  "Luigi: Menos mal que hay cabezas que piensan en este grupo",
  "Xoana: Jajaja, es que tenemos un grupo paralelo en el que vamos resolviendo las crisis con antelación",
  "Luigi: Hay un cierto personaje de color verde que podria utilizar la misma tecnica si al final de décidé à venir",
  "Luigi: Erasmus?",
  "Xoana: Jajajaja",
  "Xoana: Nooo, el comité de sabias que va a Málaga",
  "Luigi: Me alegro que hayais asumido esa responsabilidad tanto como no formar parte de ese chat",
  "Xoana: Lo bueno de Shrek es que no necesita cama",
  "Xoana: Jajaja",
  "Luigi: Lo malo es que necesitamos tapones todos",
  "Xoana: Va mutando, realmente es finde Madrid",
  "Boque: Por mi perfecto 🙂",
  "Boque: Fueron 127,60€ cada uno por lo que acabo de ver",
  "Luigi: Angel como buen visitador parafarmaceutico pagara su parte en especias",
  "Ángel: 🤣🤣🤣🤣",
  "Alberto: Voy a revisar cuándo me pillé los vuelos y los hoteles, que no recuerdo nada",
  "Alberto: De jueves a martes 🤷🏿‍♂️",
  "Alberto: A martes? Vaya tela",
  "Ángel: Abres y cierras la reunión..👏🏻👏🏻👏🏻",
  "Ángel: Laura y tu ya empezáis el jueve erasmus!!",
  "Alberto: Me da tiempo a pasarla a limpio. Y vuelvo ahora de Bélgica de lo mismo (nos hemos comportado)",
  "Ángel: Los años no pasan por ti Albert!!",
  "Alberto: Pasan por encima de mí como una apisonadora",
  "Alberto: Jueves y domingo tengo reservado aquí.",
  "Alberto: https://maps.app.goo.gl/wjzdgv7n4MvLg6rE9?g_st=ic",
  "Laura: Hay Carmilla en Málaga?",
  "Boque: Hay cosas peores, os paso recomendaciones esa semana 😂😂😂",
  "Boque: Pero no os desfondéis!",
  "Boque: Familia, ya está todo completo para la noche del 19 de abril en el sitio al que os quería llevar a cenar 😬",
  "Boque: Estoy pensando (por no repetir pescaito frito, que es lo que comemos al medio día) en mexi, sushi o fusión",
  "Boque: algún problema con alguno de esos tipos de comida?",
  "Luigi: Nos fiamos de ti boque",
  "Luigi: A mi mola todo",
  "Luigi: Mex dpm",
  "Lolina: Ninguno!",
  "Luigi: Pero me adapto",
  "Boque: Por ahora mexi entonces",
  "Luigi: Tapeo malagueño me va de lujo tb",
  "Lolina: Si os enseño cosas que comí en Singapur …",
  "Ángel: Muy mal Boque  yo ya no voy",
  "Lolina: Vamos, que me adapto al 100%",
  "Boque: Ya, el rollo es que en los sitios de tapeo no reservan, y ya no están la cosas para ir a la aventura, nos pueden dar las mil y que encima comamos mal",
  "Ángel: Busca algo típico Málaga..",
  "Boque: Tu sácate el billete ya, mamón ‎<Se editó este mensaje.>",
  "Boque: No te precoupes",
  "Lolina: Si, dos personas improvisas, 8 es jugársela mucho!",
  "Luigi: Si nos quedamos con hombre ya comeremos un poco de techo",
  "Boque: Es que 8 no encuentras donde sentarlas tan fácil, claro",
  "Boque: Bueno, no os preocupéis",
  "Ángel: Me va a pasar con el avión lo mismo que a ti con el restaurante..",
  "Boque: Ya voy viendo",
  "Xoana: A mí me da igual, lo que te parezca.",
  "Boque: Nada, al final vamos a cenar en el italiano, que vamos a tiro hecho después de pasar por el apartamento a ducharnos y demás,  y el sábado vamos de tapas al medio día y cenamos en otro sitio",
  "Boque: Eso sí, el sábado hay que intentar no levantarse a las mil, porque entonces nos dan por saco",
  "Boque: Para esa noche, preferís pizzería napolitana u osteria romana?",
  "Boque: ‎ENCUESTA:",
  "Boque: La osteria es más restaurante serio, pero para darse un capricho está espectacular ‎<Se editó este mensaje.>",
  "Lolina: El sábado no íbamos a comer espeto?",
  "Lolina: Cuál era el plan?",
  "Boque: Sí sí",
  "Boque: Sábado comemos pescaito",
  "Boque: espetos lamentablemente no Loles, sólo se comen los meses sin “r”",
  "Lolina: Ah!",
  "Lolina: 😂😂😂😂",
  "Boque: jajajaja",
  "Xoana: Al contrario que el marisco",
  "Lolina: Pero al revés",
  "Lolina: Si si jajajajaj",
  "Lolina: Qué cacao",
  "Boque: Aquí la sardina buena es de mayo a agosto",
  "Boque: El resto para los guiris",
  "Boque: y los madrileños 😂😂😂",
  "Lolina: Confío en el cambio climático",
  "Xoana: Fodechinchos",
  "Xoana: 😊",
  "Lolina: Si alguno es capaz de levantarse a las mil a estas alturas del partido le hago la ola",
  "Xoana: ¿El sábado comemos en un sitio más de batalla?",
  "Boque: Por eso, el plan por ahora confirmado es:",
  "Boque: Perdón por las correcciones",
  "Boque: Sí, el sábado vamos a ir de bar en bar picando",
  "Xoana: Ah me lié. Creí que estábamos pensando donde cenar el sábado. Es el viernes vale",
  "Boque: Fallo mio, me expliqué mal",
  "Boque: El *SABADO* de entrada para comer las cosas serían así:",
  "Xoana: Pues osteria 👍",
  "Xoana: Pero en cualquier caso que esto no sea un estrés, todo nos parecerá bien.",
  "Boque: Nada será un estrés, esto es Andalucía 😂",
  "Boque: Pero sí quiero tenerlo todo más o menos atado (menos la comida del sábado que vamos de tapeo), por no encontrarnos de repente con todo lleno y sin opciones, y para las copas igual ‎<Se editó este mensaje.>",
  "Boque: Bueno, cuando vaya cerrando el resto de sitios os voy informando",
  "Boque: Buena semana santa! 😘😘😘"
];
